-------GENERATED BY TESTBUDDY-------
----Replace UPDATE-ME placeholder with required value----
----Also, update test steps with required inputs----

# getEmployees

* request setup


## TEST_200 Perform 200 OK Scenario
* use path "/employees"
* send "GET" http request
* Then response status code is "200"
* The response content-type should be "application/json"
